In [138]:
## Objectives of Analysis

'''The following insights are derived from the dataset:

- Analyze the relationship between study hours and student marks
- Examine how attendance impacts academic performance
- Calculate average performance across subjects
- Identify low-performing students based on marks and attendance
- Determine the most challenging subject using score variability'''

### Assumption
# Missing grade values are treated as 0, assuming absent students received a score of 0.









import pandas as pd
import numpy as np

In [139]:
df=pd.read_csv("student_performance_dataset.csv")

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          200 non-null    int64
 1   Age                 200 non-null    int64
 2   Gender              200 non-null    object
 3   Math_Marks          184 non-null    float64
 4   Science_Marks       184 non-null    float64
 5   English_Marks       184 non-null    float64
 6   Attendance_Percent  184 non-null    float64
 7   Study_Hours         184 non-null    float64
dtypes: float64(5), int64(2), object(1)
memory usage: 11.8+ KB

In [141]:
df.head(10)

,Student_ID,Age,Gender,Math_Marks,Science_Marks,English_Marks,Attendance_Percent,Study_Hours
0,1,24,F,75.0,42.0,49.0,83.0,NaN
1,2,21,M,72.0,57.0,73.0,74.0,5.0
2,3,22,M,43.0,80.0,81.0,NaN,1.5
3,4,24,F,72.0,46.0,82.0,76.0,1.8
4,5,20,F,53.0,63.0,63.0,64.0,4.0
5,6,22,F,NaN,70.0,52.0,88.0,5.5
6,7,22,F,87.0,96.0,92.0,63.0,2.2
7,8,24,F,59.0,NaN,89.0,69.0,3.7
8,9,19,F,95.0,53.0,45.0,76.0,4.3
9,10,20,F,47.0,67.0,66.0,69.0,3.0

In [142]:
df.describe()

,Student_ID,Age,Math_Marks,Science_Marks,English_Marks,Attendance_Percent,Study_Hours
count,200.000000,200.000000,184.000000,184.000000,184.000000,184.000000,184.000000
mean,100.500000,21.170000,72.179348,69.809783,69.347826,78.266304,3.351087
std,57.879185,2.002787,16.802791,15.451023,14.795461,11.486260,1.465337
min,1.000000,18.000000,40.000000,42.000000,45.000000,60.000000,0.600000
25%,50.750000,19.000000,61.000000,57.000000,57.000000,68.750000,2.200000
50%,100.500000,21.000000,72.000000,70.000000,70.000000,78.500000,3.400000
75%,150.250000,23.000000,86.000000,83.000000,81.250000,87.250000,4.600000
max,200.000000,24.000000,99.000000,97.000000,94.000000,99.000000,6.000000

In [143]:
df['Math_Marks']=df['Math_Marks'].fillna(0)

In [144]:
df['Science_Marks']=df['Science_Marks'].fillna(0)

In [145]:
df['English_Marks']=df['English_Marks'].fillna(0)

In [146]:
df['Attendance_Percent']=df['Attendance_Percent'].fillna(df['Attendance_Percent'].mean().round(2))

In [147]:
df['Study_Hours']=df['Study_Hours'].fillna(df['Study_Hours'].mean().round(2))

In [148]:
df["Average_Marks"] = df[["Math_Marks", "Science_Marks", "English_Marks"]].mean(axis=1).round(2)

In [149]:
study=pd.to_numeric(df['Study_Hours'],errors='coerce').to_numpy()
avg_marks = df["Average_Marks"].to_numpy()
np.corrcoef(study, avg_marks)

array([[ 1.        , -0.12948757],
       [-0.12948757,  1.        ]])

**Inference:** The correlation value (~ -0.13) indicates a very weak relationship between study hours and average marks.

In [150]:
attendance=df['Attendance_Percent'].to_numpy()

In [151]:
np.corrcoef(avg_marks,attendance)

array([[1.        , 0.00738985],
       [0.00738985, 1.        ]])

**Inference:** Attendance shows almost no relationship with overall student performance.

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          200 non-null    int64
 1   Age                 200 non-null    int64
 2   Gender              200 non-null    object
 3   Math_Marks          200 non-null    float64
 4   Science_Marks       200 non-null    float64
 5   English_Marks       200 non-null    float64
 6   Attendance_Percent  200 non-null    float64
 7   Study_Hours         200 non-null    float64
 8   Average_Marks       200 non-null    float64
dtypes: float64(6), int64(2), object(1)
memory usage: 13.4+ KB

In [153]:
df.head(10)

,Student_ID,Age,Gender,Math_Marks,Science_Marks,English_Marks,Attendance_Percent,Study_Hours,Average_Marks
0,1,24,F,75.0,42.0,49.0,83.00,3.35,55.33
1,2,21,M,72.0,57.0,73.0,74.00,5.00,67.33
2,3,22,M,43.0,80.0,81.0,78.27,1.50,68.00
3,4,24,F,72.0,46.0,82.0,76.00,1.80,66.67
4,5,20,F,53.0,63.0,63.0,64.00,4.00,59.67
5,6,22,F,0.0,70.0,52.0,88.00,5.50,40.67
6,7,22,F,87.0,96.0,92.0,63.00,2.20,91.67
7,8,24,F,59.0,0.0,89.0,69.00,3.70,49.33
8,9,19,F,95.0,53.0,45.0,76.00,4.30,64.33
9,10,20,F,47.0,67.0,66.0,69.00,3.00,60.00

In [154]:
df[["Math_Marks", "Science_Marks", "English_Marks"]].mean()

Math_Marks       66.405
Science_Marks    64.225
English_Marks    63.800
dtype: float64

**Inference:** The average marks vary across subjects, indicating differences in subject difficulty.

In [155]:
overall_avg = df["Average_Marks"].mean()
overall_avg

np.float64(64.80975000000001)

In [156]:
low_performers = df[df["Average_Marks"] < overall_avg]
low_performers

,Student_ID,Age,Gender,Math_Marks,Science_Marks,English_Marks,Attendance_Percent,Study_Hours,Average_Marks
0,1,24,F,75.0,42.0,49.0,83.0,3.35,55.33
4,5,20,F,53.0,63.0,63.0,64.0,4.00,59.67
5,6,22,F,0.0,70.0,52.0,88.0,5.50,40.67
7,8,24,F,59.0,0.0,89.0,69.0,3.70,49.33
8,9,19,F,95.0,53.0,45.0,76.0,4.30,64.33
...,...,...,...,...,...,...,...,...,...
187,188,24,M,40.0,51.0,83.0,68.0,5.20,58.00
190,191,21,F,40.0,0.0,82.0,94.0,4.80,40.67
193,194,20,F,71.0,54.0,62.0,99.0,5.90,62.33
196,197,21,M,64.0,50.0,71.0,67.0,3.20,61.67
198,199,19,M,84.0,68.0,0.0,96.0,4.60,50.67

**Inference:** Students scoring below the overall average were identified as low-performing.

**Data Cleaning Completed:** Missing values were handled, data types were corrected, and the dataset was prepared for analysis.

In [157]:
df.to_csv("FINAL_dataset.csv", index=False)

from IPython.display import FileLink
FileLink("FINAL_dataset.csv")

/drive/FINAL_dataset.csv